# Generated by Django 5.2.1 on 2025-05-16 20:34

from django.db import migrations

def forwards_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Author = apps.get_model('myapp', 'Author')
    
    for author in Author.objects.all():
        user = User.objects.create(
            username=f"{author.name}_{author.id}",
            name=author.name,
            email=author.email
        )
        author.user = user
        author.save()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
    ]
